abstract class FilterStates {}

class FilterInitialState extends FilterStates{}

class FilterCoursesListWithInstructorNameInFilterCubit extends FilterStates{}

class CloseFilterCoursesListWithInstructorNameInFilterCubit extends FilterStates{}

class ChangeFromDateContainerValueStateInFilterCubit extends FilterStates{}

class ChangeToDateContainerValueStateInFilterCubit extends FilterStates{}

class FilterCoursesListWithDatesInFilterCubit extends FilterStates{}

class CloseFilterCoursesListWithDatesInFilterCubit extends FilterStates{}

class SchoolChangeInstructorNameInMenuStateInFilterCubit extends FilterStates{}
